### PR TITLE
Adding GPT 4o model

### LINKED ISSUE #55: New GPT models
Should I see new models like GPT-4o? Or is that the -0613?

image

### PR DESCRIPTION
**Pull request by mlazzarotto**
Fixes #55

### CODE REVIEW

**Comment by MichielvanBeers** [comment]
Thanks for adding this @mlazzarotto, much appreciated 🙏🏻! Could you also bump the version number in the plugin.json file? I can do it as well, but then it would be at the end of this week.

**Comment by mlazzarotto** [comment]
Sure, I bumped the minor version number

**Review by MichielvanBeers — APPROVED** [review]
Awesome! Approved.

**Comment by MichielvanBeers** [comment]
It can take a couple of hours for it to become available through FlowLauncher

**Pull request merged**
